language: elixir

notifications:
  email: false

elixir:
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.4.1
  - 1.4.2

otp_release:
  - 19.3
  - 19.0

script:
  - mix local.rebar --force
  - mix local.hex --force
  - make dist
